---
name: Update data/kss-report.csv

on:
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch:

jobs:
  report:
    name: KSS Github Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # fetch statistics for @octokit org
      - uses: gr2m/org-stats-action@v1.x
        id: stats
        with:
          org: keep-starknet-strange
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # append stats to data/octokit.csv
      - name: Get data
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: gr2m/write-csv-file-action@v1.x
        with:
          path: data/kss-report-${{ steps.date.outputs.date }}.csv
          columns: open_issues,closed_issues,open_pull_requests,closed_pull_requests,merged_pull_requests
          "open_issues": ${{ fromJson(steps.stats.outputs.data).openIssues }}
          "closed_issues": ${{ fromJson(steps.stats.outputs.data).closedIssues }}
          "open_pull_requests": ${{ fromJson(steps.stats.outputs.data).openPullRequests }}
          "closed_pull_requests": ${{ fromJson(steps.stats.outputs.data).closedPullRequests }}
          "merged_pull_requests": ${{ fromJson(steps.stats.outputs.data).mergedPullRequests }}
      # push updated file back to main branch
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: git add data
      - run: git commit -m "data/kss-report-${{ steps.date.outputs.date }}.csv updated"
      - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          